---

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Group
      ec2_group:
        name: General group
        description: Allow admin connection
        region: us-east-2
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80

    - name: Provision a set of instances
      ec2:
         key_name: myKey
         group: General group
         instance_type: t2.micro
         image: "ami-07c1207a9d40bc3bd"
         wait: true
         exact_count: 2
         region: us-east-2
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2

    - name: Refresh inventory
      meta: refresh_inventory

    - name: Whait VM init
      when: ec2.changed
      pause:
        minutes: 1

- hosts: aws_ec2
  gather_facts: true
  become: true
  vars:
    - ansible_user: ubuntu
  tasks:
    - name: Install nginx
      yum:
        name: nginx

    - name: Service enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Main page
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        regexp: "<h1>.*"
        line: "<h1>Welcome to host {{ ansible_hostname }}</h1>"