---

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: myKey
         group: test
         instance_type: t2.micro
         image: "ami-07c1207a9d40bc3bd"
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
      register: ec2